matrix:
  include:
    - language: android
      os: linux
      dist: bionic
      jdk: oraclejdk8
      android:
        components:
          - build-tools-29.0.3
          - android-5
          - android-29
       before_script:
         - cd android
       script:
         - ./gradlew build
    - language: cpp
      os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libfreetype6-dev:i386
            - libfontconfig-dev:i386
            - p7zip-full
            - cmake
            - cmake-data
            - ninja-build
      script:
        - cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Debug
        - ninja -v