language: cpp
git:
  submodules: true
jobs:
  include:
    - stage: build
      name: "Build for Linux"
      cache: ccache
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libfreetype6-dev:i386
            - libfontconfig-dev:i386
            - p7zip-full
      env: ARCH=i686
      script:
        - ./waf -T debug configure build -v
      before_deploy:
        - mv */*/*.so .
        - 7z a -t7z tf15-client-linux.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on *.so
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        tag_name: "travis-ci"
        file: tf15-client-linux.7z
        skip_cleanup: true
        overwrite: true
    - stage: build
      name: "Build for Windows"
      cache: ccache
      os: windows
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
      script:
        - ./waf -T debug configure build -v
      before_deploy:
        - mv */*/*.dll */*/*.pdb .
        - 7z a -t7z tf15-client-win32.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on *.dll *.pdb
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        tag_name: "travis-ci"
        file: tf15-client-win32-msvc.7z
        skip_cleanup: true
        overwrite: true