branches:
  except:
  - travis-ci

matrix:
  include:
    - language: android
      os: linux
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - tools
          - build-tools-29.0.3
          - android-5
          - android-29
          - extra-google-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "ndk;21.0.6113669"
      before_script:
        - cd android
      script:
        - ./gradlew build
      before_deploy:
        - mv app/build/outputs/apk/debug/app-debug.apk tf15-client.apk
        - export TRAVIS_TAG=travis-ci
        - git tag -f $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file: "tf15-client.apk"
        skip_cleanup: true
        prerelease: true
        overwrite: true
    - language: cpp
      os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libfreetype6-dev:i386
            - libfontconfig-dev:i386
            - p7zip-full
            - cmake
            - cmake-data
            - ninja-build
      script:
        - cmake -H. -Bbuild -G Ninja
        - cd build
        - cmake --build . --config Debug
      before_deploy:
        - tar -czvf tf15-client.tar.gz **/*menu*.so **/*client*.so
        - export TRAVIS_TAG=travis-ci
        - git tag -f $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file: "tf15-client.tar.gz"
        skip_cleanup: true
        prerelease: true
        overwrite: true
    - language: cpp
      os: windows
      compiler: msvc
      script:
        - cmake -A Win32 -H. -Bbuild
        - cd build
        - cmake --build . --config Debug